language: node_js
node_js:
  - 9.11.2
script:
  - git clone https://github.com/xieguanglei/amberpine.git
  - cd amberpine
  - npm install
  - cd ../
  - node amberpine/src/cli.js
branches:
  only:
  - source
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: source
  target_branch: master