language: node_js
node_js:
  - 9.11.2
script:
  - npm install amberpine
  - node_modules/.bin/abp
  - cp .nojekyll dist
branches:
  only:
  - source
deploy:
  provider: pages
  local_dir: dist
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: source
  target_branch: master