language: node_js
node_js:
  - 9.11.2
script:
  - git checkout master
  - git merge source
  - git clone git@github.com:xieguanglei/amberpine.git
  - cd amberpine
  - npm install
  - cd ../
  - node amberpine/src/cli.js

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: ./
  github_token: $GITHUB_TOKEN
  on:
    branch: master
